"""
Refresh results/latest/ — the copy of the newest export that leads the results tree.

results/latest/ is bind-mounted onto the host, so every path here writes to the host
disk for real. That is why this module is separate: its invariants are about not
writing outside the directory it owns, while the rest of the export is about what a
run produced. Copying a parent of latest_dir once recursed six levels deep and wrote
~100GB of duplicated Hugging Face cache to the host.
"""

from __future__ import annotations

import logging
import os
import shutil
import stat
import tempfile
from pathlib import Path

logger = logging.getLogger(__name__)

# Read independently of run_results so this module depends on nothing above it —
# run_results imports refresh_latest, not the other way round.
LATEST_DIR = Path(os.environ.get("REPO_ROOT", "/app")) / "results" / "latest"


_LATEST_README_INTRO = """<!-- Generated by the pipeline: edits here are overwritten. -->
# Latest results — {title}

Copied from [`results/runs/{source}/`]({source_link}), which is the permanent home of
this export. Anything in `results/latest/` is replaced by the next run.

{files}
---

"""


# results/latest/ is a bind mount onto the host, so anything copied here is written
# to the host disk for real. Two invariants keep that bounded, and both are enforced
# below rather than trusted: the source is one export folder that does not contain
# latest_dir, and only flat text artifacts are copied — never a subtree, a cache, or
# model weights. Copying a parent of latest_dir once recursed six levels deep and
# wrote ~100GB of duplicated Hugging Face cache to the host.
SNAPSHOT_SUFFIXES = frozenset({".csv", ".json", ".jsonl", ".md", ".txt", ".yaml", ".yml"})
SNAPSHOT_MAX_BYTES = 64 * 1024 * 1024
# Per-file size alone bounds nothing: a run folder of many just-under-cap files still
# lands on the host disk. The total is what the host actually pays.
#
# It bounds the artifacts *copied from the source*, not the total bytes written: the
# README refresh_latest generates afterwards embeds summary.md's body and is not
# counted, so the directory can exceed this by roughly one summary. That is deliberate
# — the README is the point of the folder, and dropping it to satisfy an accounting
# rule would be the wrong trade. The number is a bound on what a runaway source can
# push onto the host, not a promise about the directory's final size.
SNAPSHOT_MAX_TOTAL_BYTES = 256 * 1024 * 1024
# The half-written files _replace_artifact renames into place. A crash between mkstemp
# and the rename leaves one behind, so the clear step removes them: they are this
# function's own litter, and telling a human to delete them by hand would be reporting
# our mess as theirs.
SNAPSHOT_TEMP_PREFIX = ".snapshot-"

# The files the snapshot README links, and why each is worth opening.
SNAPSHOT_HIGHLIGHTS = {
    "by_question.md": "every question, side by side across approaches",
    "cpu_vs_cuda.json": "aggregate CPU vs GPU deltas, machine readable",
    "evaluation_metrics.csv": "one row per question, straight from Postgres",
    "manifest.json": "what ran, on which hardware",
    "by_question_throughput.csv": "tokens/sec per question × approach × device",
    "by_question_latency.csv": "time_to_response per question × approach × device",
}

# What the aggregate cap must keep when it cannot keep everything. Alphabetical order
# sheds manifest.json before by_question*.json, which costs the snapshot its run
# identity — which run, on which hardware — while keeping bulk per-question data that
# is then unattributable. Identity and the human summary come first, then the files
# the README links, then everything else.
SNAPSHOT_PRIORITY = ("manifest.json", "summary.md") + tuple(
    name for name in SNAPSHOT_HIGHLIGHTS if name != "manifest.json"
)


def _snapshot_order(source_dir: Path) -> list[Path]:
    """`source_dir` entries, most worth keeping first, then the rest alphabetically."""
    remaining = {entry.name: entry for entry in sorted(source_dir.iterdir())}
    ordered = [remaining.pop(name) for name in SNAPSHOT_PRIORITY if name in remaining]
    return ordered + list(remaining.values())


def _atomic_write(dest: Path, fill) -> None:
    """
    Put bytes at `dest` without any step following a symlink that may sit there.

    `fill(out)` writes to a descriptor mkstemp opened on a file it created
    exclusively; the path is never reopened by name, so a link appearing at it
    afterwards has nothing left to redirect. Permissions and timestamps are set on
    that same descriptor rather than through `shutil.copystat`, which takes a path
    and would follow such a link.

    One window remains, between closing the descriptor and `os.replace`: a link
    swapped in there is installed at `dest` by the rename — `os.replace` does not
    follow symlinks — orphaning the bytes just written. Nothing follows that link:
    the next refresh's clear loop removes it before anything reads or writes it. It
    costs one stale snapshot, not a write outside results/latest, so it is left.
    """
    fd, tmp_name = tempfile.mkstemp(dir=dest.parent, prefix=SNAPSHOT_TEMP_PREFIX)
    tmp = Path(tmp_name)
    try:
        with os.fdopen(fd, "wb") as out:
            fill(out)
        os.replace(tmp, dest)
    except BaseException:
        tmp.unlink(missing_ok=True)
        raise


def _replace_artifact(src: Path, dest: Path) -> None:
    """Copy `src` onto `dest`, carrying its mode and mtime, following no symlink."""
    info = src.stat()

    def fill(out):
        with open(src, "rb") as reader:
            shutil.copyfileobj(reader, out)
        os.fchmod(out.fileno(), stat.S_IMODE(info.st_mode))
        if os.utime in os.supports_fd:
            os.utime(out.fileno(), ns=(info.st_atime_ns, info.st_mtime_ns))

    _atomic_write(dest, fill)


def _write_snapshot_text(dest: Path, text: str) -> None:
    """Write generated text (the README) as safely as a copied artifact."""
    _atomic_write(dest, lambda out: out.write(text.encode("utf-8")))


def _report_snapshot_residue(latest_dir: Path) -> None:
    """
    Name whatever the clear step deliberately left behind.

    Leaving unrelated files is the policy — it is what stops a mistargeted destination
    from being destroyed. Leaving them *silently* is the problem: a directory here is
    skipped by every step of a refresh, and a results/latest/results/ left by the old
    recursive copy then aborts the pipeline at startup with nothing saying that the
    export will not clear it either. Only a human deleting it resolves that state.
    """
    residue = sorted(
        f"{entry.name}/" if entry.is_dir() else entry.name
        for entry in latest_dir.iterdir()
        if entry.is_dir() or entry.suffix.lower() not in SNAPSHOT_SUFFIXES
    )
    if residue:
        logger.warning(
            "Snapshot left %d unrelated entries in %s (refresh does not remove these; "
            "delete them by hand if they are stale): %s",
            len(residue),
            latest_dir,
            ", ".join(residue),
        )


def _snapshot_artifacts(source_dir: Path) -> list[Path]:
    """Files in `source_dir` eligible for results/latest/ — flat, small, text."""
    keep: list[Path] = []
    skipped: list[str] = []
    total = 0
    for entry in _snapshot_order(source_dir):
        if not entry.is_file() or entry.is_symlink():
            skipped.append(f"{entry.name} (not a regular file)")
            continue
        if entry.suffix.lower() not in SNAPSHOT_SUFFIXES:
            skipped.append(f"{entry.name} ({entry.suffix or 'no suffix'} is not an artifact type)")
            continue
        size = entry.stat().st_size
        if size > SNAPSHOT_MAX_BYTES:
            skipped.append(f"{entry.name} ({size} bytes, over the {SNAPSHOT_MAX_BYTES} per-file cap)")
            continue
        if total + size > SNAPSHOT_MAX_TOTAL_BYTES:
            skipped.append(
                f"{entry.name} ({size} bytes would pass the {SNAPSHOT_MAX_TOTAL_BYTES} total cap)"
            )
            continue
        total += size
        keep.append(entry)
    if skipped:
        logger.warning(
            "Snapshot of %s kept %d files (%d bytes) and skipped %d: %s",
            source_dir,
            len(keep),
            total,
            len(skipped),
            "; ".join(skipped),
        )
    return keep


def refresh_latest(source_dir: Path, latest_dir: Path | None = None) -> Path:
    """
    Replace results/latest/ with the artifacts of `source_dir`, led by a README.

    The README is the folder's summary rather than a pointer to one, so it is what
    GitHub and most file browsers show first, and it names the run it came from.
    """
    source_dir = Path(source_dir)
    latest_dir = Path(latest_dir or LATEST_DIR)

    if not source_dir.is_dir():
        raise NotADirectoryError(f"Snapshot source is not a directory: {source_dir}")
    source_resolved = source_dir.resolve()
    latest_resolved = latest_dir.resolve()

    # The destination is the one directory this function owns. Checking its shape
    # first means transposed arguments — refresh_latest(run_dir, repo_root) — are
    # rejected before anything is deleted, rather than clearing the repo.
    #
    # Deliberately name-based, not anchored to RESULTS_DIR: that constant is
    # REPO_ROOT/results with REPO_ROOT defaulting to /app, while 08_compare_devices
    # and 09_compare_runtimes both accept --repo-root and every test builds its tree
    # under tmp_path. Anchoring would reject those legitimate callers and force a
    # test-only escape hatch, which is worse than the narrow exposure it closes: any
    # */results/latest passes, but a destination named neither cannot.
    if latest_resolved.name != "latest" or latest_resolved.parent.name != "results":
        raise ValueError(
            f"Refusing to snapshot into {latest_dir}: the destination must be a "
            "results/latest/ directory. Check the argument order — the source "
            "folder comes first."
        )
    if latest_resolved == source_resolved or latest_resolved.is_relative_to(source_resolved):
        raise ValueError(
            f"Refusing to snapshot {source_dir} into {latest_dir}: the destination is "
            "inside the source, which copies the tree into itself. Pass the single "
            "export folder (results/runs/<run_id>/), not a parent of it."
        )
    if source_resolved.is_relative_to(latest_resolved):
        raise ValueError(
            f"Refusing to snapshot {source_dir} into {latest_dir}: the source is inside "
            "the destination, so clearing the destination would delete the source first."
        )

    artifacts = _snapshot_artifacts(source_dir)
    # Clear by unlinking the artifact types this function writes, never by removing
    # the directory: a mistargeted destination that slipped past the checks above
    # then loses at most files of those types instead of its whole tree. README.md
    # is covered by `.md`.
    #
    # Symlinks go unconditionally, whatever they point at or are named. results/ is a
    # container-writable bind mount, so a link planted there is a write outside
    # results/ waiting for the next snapshot to follow it — copying onto a symlinked
    # destination writes through to its target.
    latest_dir.mkdir(parents=True, exist_ok=True)
    for stale in latest_dir.iterdir():
        if stale.is_symlink():
            logger.warning("Snapshot removes symlink %s -> %s", stale, os.readlink(stale))
            stale.unlink()
        elif stale.is_file() and (
            stale.suffix.lower() in SNAPSHOT_SUFFIXES
            or stale.name.startswith(SNAPSHOT_TEMP_PREFIX)
        ):
            stale.unlink()

    _report_snapshot_residue(latest_dir)

    for artifact in artifacts:
        _replace_artifact(artifact, latest_dir / artifact.name)

    # A link here is never legitimate — the clear loop says so — and read_text would
    # follow it, folding a host file's contents into the README this writes. Treat it
    # as absent, exactly as if the source had no summary.
    summary = latest_dir / "summary.md"
    if summary.is_symlink():
        logger.warning("Snapshot ignores symlinked summary.md -> %s", os.readlink(summary))
        summary.unlink()
        body = ""
    else:
        body = summary.read_text(encoding="utf-8") if summary.is_file() else ""
    # summary.md's own H1 would collide with the README's, and keeping both files
    # would leave two copies of the same text to drift apart.
    body = "\n".join(line for line in body.splitlines() if not line.startswith("# "))
    summary.unlink(missing_ok=True)

    listed = [
        f"- [`{name}`](./{name}) — {why}"
        for name, why in SNAPSHOT_HIGHLIGHTS.items()
        if (latest_dir / name).is_file()
    ]
    files = "**In this folder**\n\n" + "\n".join(listed) + "\n\n" if listed else ""

    # write_text follows a symlink planted here after the clear loop ran, which is an
    # arbitrary host write. The one file written on every refresh takes the safest
    # path, not the least safe one.
    _write_snapshot_text(
        latest_dir / "README.md",
        _LATEST_README_INTRO.format(
            title=source_dir.name,
            source=source_dir.name,
            source_link=f"../runs/{source_dir.name}/",
            files=files,
        )
        + body.lstrip("\n"),
    )
    return latest_dir
